//EXEMPLO 1
 let tarefaConcluida: boolean = true;

   if (!tarefaConcluida) {
       console.log('Tarefa Pendente!');
  } else {
       console.log('Tarefa Concluída COM SUCESSO!');
}








//EXEMPLO 2
let idade: number = 20;

let maioridade: boolean = idade >= 18;

if (maioridade) {

    console.log ('É maior de idade.');

} else {
    
    console.log ('É menor de idade.');
}

// isso vai verificar se pessoa é maior de idade.

